Repository AKVorrat/dearmep, pull requests merged in 2025-09, with the labels that each got.

#311 Support reading zstd Parltrack MEP dumps
  doc/data-conversion.md
  server/dearmep/cli/convert.py
  server/dearmep/convert/parltrack/mep.py
  server/dearmep/convert/zstd.py
  server/pyproject.toml
  server/uv.lock
Labels: type:enhancement, area:backend

#321 Python security updates 2025-09-16
  server/Makefile
  server/pyproject.toml
  server/uv.lock
Labels: type:enhancement, area:backend, flag:security, prio:A

#322 Return 400 when verifying invalid phone numbers
  server/dearmep/api/v1.py
  server/tests/api/test_number_verification.py
Labels: type:bug, area:backend, prio:B

#325 Remove `category` from 46elks phone numbers
  server/dearmep/phone/elks/models.py
Labels: type:bug, area:backend, prio:A

#329 Bump Pydantic 1.10.19 → 1.10.23
  server/pyproject.toml
  server/uv.lock
Labels: type:bug, area:backend, prio:C

#327 Apply primary button text color to small primary button as well
  client/src/style/dear-mep-inner.scss
Labels: type:enhancement, area:frontend, prio:C

#331 Improve logging for `error_model` based responses
  server/dearmep/api/v1.py
Labels: type:enhancement, area:backend, prio:C

#332 Allow setting a time limit for conversations
  server/dearmep/config.py
  server/dearmep/example-config.yaml
  server/dearmep/phone/elks/elks.py
Labels: type:enhancement, area:backend, prio:B
